name: Deploy to DigitalOcean Functions

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Create deployment package
      run: zip -r deployment.zip .

    - name: Upload deployment package
      uses: actions/upload-artifact@v2
      with:
        name: deployment-package
        path: deployment.zip

    - name: Download deployment package
      uses: actions/download-artifact@v2
      with:
        name: deployment-package
        path: deployment.zip

    - name: Install doctl
      run: |
        curl -sL https://github.com/digitalocean/doctl/releases/download/v1.66.0/doctl-1.66.0-linux-amd64.tar.gz | tar -xzv
        sudo mv doctl /usr/local/bin

    - name: Authenticate doctl
      env:
        DIGITALOCEAN_ACCESS_TOKEN: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      run: doctl auth init -t $DIGITALOCEAN_ACCESS_TOKEN

    - name: Deploy to DigitalOcean Functions
      env:
        DIGITALOCEAN_ACCESS_TOKEN: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      run: doctl serverless deploy deployment.zip --namespace <your-namespace> --package <your-package-name>
